### ISSUE TITLE
Error encountered installing CLI on macbook

### ISSUE THREAD

**Issue by magicpia** [magic-network/magic-cli#4]
Submitting as a GitHub issue via @drmartens 

cc: @villavicencio @sfoulkes due to https://github.com/magic-network/magic-cli/pull/3

----
I'm having some trouble installing the Magic-CLI on my Macbook Pro. I cleaned up my Python versions and uninstalled and reinstalled PIP, but no dice.

This is the error I'm having. I am using Python 2.7 and the below Pip version and distribution --   pip 18.1 from /Library/Python/2.7/site-packages/pip (python 2.7)

```
Could not find a version that satisfies the requirement magic-cli (from versions: )
No matching distribution found for magic-cli
```

**Comment by AshtonHamm** [comment]
I have a similar problem on my MacBook Air (OSX 10.13) that the solution #6 did not solve.
Complete output from command python setup.py egg_info:
    
    Installed /private/var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/pip-install-wjIifm/eth-keys/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.4
    Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#sha256=e914e6d5f84a76764887e4d909b09d63308725f0cbb5293872c2c92f07c11a5b
    Processing pypandoc-1.4.tar.gz
    Writing /var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/easy_install-ASXcPj/pypandoc-1.4/setup.cfg
    Running pypandoc-1.4/setup.py -q bdist_egg --dist-dir /var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/easy_install-ASXcPj/pypandoc-1.4/egg-dist-tmp-oeOUEu
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    creating /private/var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/pip-install-wjIifm/eth-keys/.eggs/pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to /private/var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/pip-install-wjIifm/eth-keys/.eggs
    
    Installed /private/var/folders/9r/tsctkqp12t3d84jlc1_3bs600000gn/T/pip-install-wjIifm/eth-keys/.eggs/pypandoc-1.4-py2.7.egg
    error in eth-keys setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in eth-utils>=0.5.0<1.0.0 at <1.0.0




Specifically, this error line in particular:

    error in eth-keys setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in eth-utils>=0.5.0<1.0.0 at <1.0.0

**Comment by ozymandias547** [comment]
This looks like it could be an issue with eth-keys and the version of setuptools. Please try updating them with:

`pip install --user -U setuptools`

it's possible eth-keys  has utilized a newer feature of setuptools, and made it backwards incompatible. A version that has been working for us is `setuptools (40.6.2)`.

**Comment by AshtonHamm** [comment]
Like MAGIC, your solution worked @ozymandias547 ! :D
Tried your command in my virtual environment first and received this error:
> Requirement already up-to-date: setuptools in /Users/AshtonHamm/MAGIC/magic-env/lib/python3.5/site-packages

Using the command outside of the virtual environment on my system-wide python interpreter correctly retrieved the packages! 

`pip install setuptools`  did not work for me before, but changing that to:
`pip install --user -U setuptools` solved the problem!

However, I had to do
`pip install --user .`
instead of the recommended
`pip install .`
due to environment errors on my machine. 

Whenever I attempt to start the CLI with magic-cli though, I am met with this error:

> The script magic-cli is installed in '/Users/AshtonHamm/Library/Python/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

So, it did install the magic-cli, but I have to go one more directory deep and execute the magic-cli with:
`python magic-cli`
at
> ~/Library/Python/2.7/magic-cli/

I tried adding it to my _.bash_profile_ as a PYTHONPATH, but I think I did it wrong. I am a bit unfamiliar with adding Python Environment paths. Here is what I added that did not work:

`# Add magic-cli directory to the Python Paths`

`PYTHONPATH="~/Library/Python/2.7/bin:$PYTHONPATH"`
`export PYTHONPATH`

> (PYTHONPATH Source: https://stackoverflow.com/questions/3387695/add-to-python-path-mac-os-x)

==================================================================
                                                                    SUMMARY: 
It does now work when I manually start the magic-cli at _~/Library/Python/2.7/magic-cli/_ when I use 
`python magic-cli `
    All I need to know now is how to add this to my environmental paths so I can start the CLI from anywhere using the original command of:
`magic-cli`

**Comment by ozymandias547** [comment]
Glad that worked!  With the way python package and dependency system works, we'll need to add a full blown debugging doc before the day is out X-D.  We'll note your fixes.

On a side note, if you (or anyone else for that matter) would like a quick engineer to engineer chat about the setup as a whole, I'd be happy to do that with you.

**Comment by DomAmato** [comment]
These issues both appear with python 2.7 which is slated to be [EOL in 2020](https://pythonclock.org/) so really we should impose stronger requirements to move to python 3. Still surprised its the default version on macOS 🤦‍♂ 

Should we close this since we have updated the docs to list python version > 3.5
